### ISSUE TITLE
Invalid source path in example's elm.json file

### ISSUE THREAD

**Issue by bigardone** [phollyer/elm-phoenix-websocket#3]
👋 Hi! I was going through the code, and I realized there is an invalid source path in the examples `elm.json` file, pointing to `../../../src`:

https://github.com/phollyer/elm-phoenix-websocket/blob/master/example/assets/elm/elm.json#L5

**Comment by phollyer** [comment]
That pointed to the `src` folder for the package.

**Comment by phollyer** [comment]
It's a non-issue now anyway because I've moved the example to its own repo, and deployed it live. I'm just waiting for the DNS records of the server to update, then I'll add the link to the live example to the README.

There is a link to the example repo in the README.

**Comment by bigardone** [comment]
Having it in separate repositories makes sense. :)
